### ISSUE TITLE
ConnectionRefusedError: [WinError 10061] 

### ISSUE THREAD

**Issue by ersien** [LostXine/naive-android-ssr#1]
{'adb_ip': '127.0.0.1', 'adb_port': 7555, 'adb_timeout': 9.0, 'size': [960, 540], 'bitrate': '4M'}
screenrecord --output-format=h264 --bit-rate=4M --size=960x540 -
Traceback (most recent call last):
  File "C:\Users\ersin\Documents\python\naive-android-ssr-main\main.py", line 16, in <module>
    with AndroidSSR(cfg) as assr:
  File "C:\Users\ersin\Documents\python\naive-android-ssr-main\androidssr.py", line 58, in __enter__
    if self.connect():
       ^^^^^^^^^^^^^^
  File "C:\Users\ersin\Documents\python\naive-android-ssr-main\androidssr.py", line 67, in connect
    if self.shell_pipe.connect([] if self.signer is None else [self.signer]):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ersin\AppData\Local\Programs\Python\Python312\Lib\site-packages\adb_shell\adb_device.py", line 675, in connect
    self._available, self._maxdata = self._io_manager.connect(self._banner, rsa_keys, auth_timeout_s, auth_callback, adb_info)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ersin\AppData\Local\Programs\Python\Python312\Lib\site-packages\adb_shell\adb_device.py", line 221, in connect
    self._transport.connect(adb_info.transport_timeout_s)
  File "C:\Users\ersin\AppData\Local\Programs\Python\Python312\Lib\site-packages\adb_shell\transport\tcp_transport.py", line 88, in connect
    self._connection = socket.create_connection((self._host, self._port), timeout=transport_timeout_s)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ersin\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 852, in create_connection
    raise exceptions[0]
  File "C:\Users\ersin\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 837, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] Hedef makine etkin olarak reddettiğinden bağlantı kurulamadı
PS C:\Users\ersin\Documents\python\naive-android-ssr-main>

**Comment by LostXine** [comment]
Please confirm you have a valid adb connection.

**Comment by ersien** [comment]
I made it worked! Thank you very much.
Now I want 2 things :
1- Need to turn it left like 16:9 screen
2- Use that screen for open cv.
